language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install swig
install: pip install -r requirements.txt
script: python tests/test.py unit
branches:
  only:
    - travis-ci
